language: android
jdk: oraclejdk8
sudo: false

android:
  components:
  - tools
  - platform-tools
  - build-tools-25.0.3
  - android-25
  - extra-android-support

  licenses:
  - 'android-sdk-license.*'

before_install:
  - chmod -R +x script/
  - script/accept_constraintlayout_license.sh
  - script/provide_test_apikey.sh

before_script:
  - echo no | android create avd --force -n test -t android-21 --abi armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82