language: android
jdk: oraclejdk8
sudo: false

android:
  components:
  - tools
  - platform-tools
  - build-tools-25.0.3
  - android-25
  - extra-android-support

  licenses:
  - 'android-sdk-license.*'

before_install:
  - chmod -R +x script/
  - script/provide_test_apikey.sh
  - script/accept_constraintlayout_license.sh

before_script:
  - script/emulator_setup.sh


